import telebot
import os
from dotenv import load_dotenv
from telebot.types import ReplyKeyboardMarkup, KeyboardButton


load_dotenv()
TOKEN = os.getenv("BOT_TOKEN")
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.reply_to(message, "Salom! 👋 Men Tarjimon botman. Men orqali koreys tilidagi so'zlarni qiynalmay topishingiz mumkin.")
# Lug‘at
ko_uz = {
    "학교": "maktab",
    "집": "uy",
    "자동차": "avtomobil",
    "비행기": "samolyot",
    "트럭": "truk",
    "오토바이": "mototsikl",
    "자전거": "velosiped",
    "의자": "kursi",
    "식탁": "stol",
    "책상": "parta",
    "옷": "oddiy",
    "오": "besh",
    "이": "bu, ikki, tish",
    "아우": "bola",
    "아이": "bola",
    "오이": "bodiring",
    "가수": "qo'shiqchi",
    "고기": "go'sht",
    "구두": "tufli",
    "나라": "davlat",
    "나무": "daraxt",
    "다리": "oyoq",
    "라디오": "radio",
    "머리": "bosh",
    "바나나": "banan",
    "바지": "shim",
    "소": "sigir",
    "아기": "chaqaloq",
    "어머니": "ona",
    "지도": "xarita",
    "모자": "bosh kiyim",
    "아버지": "ota",
    "허리": "bel",
    "지하": "yer osti",
    "야구": "beyzbol",
    "야자수": "palma",
    "이야기": "suxbat",
    "여자": "ayol",
    "벼": "suyak",
    "혀": "til",
    "요가": "yo'ga",
    "요리": "ovqat pishirish",
    "휴지": "tualet qog'ozi",
    "우유": "sut",
    "카드": "karta",
    "코": "burun",
    "키": "balandlik",
    "타조": "tuyaqush",
    "토마토": "pomidor",
    "투우수": "motodor",
    "파리": "pashsha, parij",
    "포도": "uzum",
    "우표": "pochta markasi",
    "차": "choy",
    "치마": "yubka",
    "고추": "qalampir",
    "커피": "kofe",
    "코트": "palto",
    "기차표": "poyezd bileti",
    "까치": "zog'cha",
    "꼬리": "dum",
    "코끼리": "fil",
    "따다": "uzmoq",
    "뜨다": "suzmoq",
    "머리띠": "abadok",
    "뿌리": "tomor , ildiz",
    "뼈": "suyak",
    "아빠": "ota",
    "싸다": "arzon",
    "쓰다": "yozmoq ,foidalanmoq",
    "아저씨": "ko'chadagi amaki",
    "짜다": "sho'r",
    "찌다": "bug'lamoq",
    "가짜": "qalbaki",
    "개미": "chumoli",
    "배": "qayiq",
    "새": "qush",
    "해": "quyosh",
    "게": "qisqichbaqa",
    "세수": "yuvinish",
    "그네": "arg'imchoq",
    "카메라": "kamera",
    "얘기": "suhbat",
    "예쁘다": "chiroyli",
    "서예": "xattotlik",
    "시계": "soat aparati",
    "과자": "pishiriq",
    "와이셔츠": "ko'ylak",
    "화가": "jaxl",
    "사과": "olma",
    "뭐": "nima",
    "줘요": "bermoq",
    "더워요": "issiq",
    "추워요": "sovuq",
    "돼지": "cho'chqa",
    "왜": "nimaga",
    "웨이터": "ofetsand",
    "스웨터": "svitr",
    "쇠고기": "cho'chqa go'shti",
    "외우다": "yodlamoq",
    "회사": "firma",
    "뚜뇌": "miyya",
    "귀": "quloq",
    "쉬다": "dam olmoq",
    "쥐": "sichqon",
    "가위": "qaychi",
    "의사": "doktor",
    "의자": "stul",
    "여의도": "yo'i oroli",
    "회의": "majlis",
    "수박": "tarvuz",
    "책": "kitob",
    "부엌": "uy oshxonasi",
    "돈": "pul",
    "레몬": "limon",
    "신문": "gazeta",
    "우산": "zontik",
    "곧": "yaqinida",
    "밑": "osti",
    "빗": "nur",
    "옷": "kiyim",
    "낮": "kunduzi",
    "꽃": "gul",
    "빛": "nur",
    "히읗": "h",
    "딸기": "qulipnay",
    "물": "suv",
    "발": "oyoq",
    "연필": "qalam",
    "곰": "ayiq",
    "남자": "erkak",
    "엄마": "ona",
    "컴퓨터": "kompyuter",
    "밥": "qaynatilgan guruch",
    "입": "og'iz",
    "무릎": "tizza",
    "숲": "o'rmon",
    "가방": "sumka",
    "공": "kopto'k",
    "냉장고": "muzlatich",
    "창문": "deraza",
    "나라": "davlat",
    "중국": "Xitoy",
    "일본": "Yaponiya",
    "미국": "AQSH",
    "한국": "Koreya",
    "프랑스": "fransiya",
    "독일": "Germaniya",
    "호주": "avstraliya",
    "영국": "Angliya",
    "빈칸": "bo'sh joy",
    "알맞다": "mos",
    "단어": "so'z",
    "선생님": "o'qituvchi",
    "학생": "o'quvchi",
    "의사": "doktor",
    "회사원": "firma ishchisi",
    "요리사": "oshpaz",
    "기자": "muxbir",
    "가수": "qo'shiqchi",
    "군인": "askar",
    "인사말": "salomlashish gapi",
    "만나다": "uchrashmoq",
    "반갑다": "xursand bo'lmoq",
    "한국말": "koreys tili",
    "그림": "surat(chizilgan)",
    "이야기하다": "suxbatlashmoq",
    "저": "men",
    "저": "anavi",
    "씨": "janob",
    "씨": "xonim",
    "네": "ha",
    "주부": "uy bekasi",
    "말하기": "gapirish",
    "어느": "qaysi",
    "캐나다": "Kanada",
    "국적": "millat",
    "묻다": "so'ramoq",
    "인도": "Xindiston",
    "직업": "kasb",
    "아니요": "yo'q",
    "여러분": "sizlar",
    "무엇": "nima",
    "러시아": "Rossiya",
    "파키스탄": "Pokiston",
    "친구": "do'st",
    "명함": "ism karta",
    "이름": "ism",
    "전화번호": "telefon raqam",
    "영어": "ingiliz tili",
    "블로그": "internetdagi blog",
    "찾다": "qidirmoq",
    "과제": "pishiriq",
    "문화": "madanyat",
    "책상": "parta",
    "의자": "stul",
    "책": "kitob",
    "공책": "daftar",
    "볼펜": "ruchka",
    "연필": "qalam",
    "가방": "sumka",
    "지우개": "o'chirg'ich",
    "시계": "soat",
    "모자": "bosh kiyim",
    "우산": "soyabon",
    "신문": "gazeta",
    "사전": "lug'at",
    "안경": "ko'zoynak",
    "휴대폰": "telefon",
    "남자친구": "yigit o'rtoq",
    "동전": "tanga",
    "차": "mashina",
    "한국어": "koreys tili",
    "여자 친구": "qiz o'rtoq",
    "뭐": "nima",
    "창문": "deraza",
    "지도": "xarita",
    "필통": "penal",
    "필통": "qalamdon",
    "전자사전": "elektron lug'at",
    "한국어로": "koreys tilida",
    "자": "chizg'ich",
    "잡지": "jurnal",
    "지갑": "hamyon",
    "여기 있어요": "marxamat",
    "커피": "kofe",
    "좀": "iltimos",
    "콜라": "ko'la",
    "주스": "sharbat",
    "교통카드": "transport kartasi",
    "휴지": "salfetka",
    "물": "suv",
    "어서 오세요": "xush kelibsiz",
    "사과": "olma",
    "오랜지": "apelsin",
    "영화": "kino",
    "우유": "sut",
    "바나나": "banan",
    "딸기": "qulipnay",
    "텔레비전": "televizor",
    "방": "non",
    "서울대학교": "Seul unversiteti",
    "제": "mening",
    "침대": "kravat",
    "룸메으트": "xonadosh",
    "에어컨": "onditsioner",
    "물건": "narsa",
    "팀": "jamoa",
    "나누다": "bo'lishmoq",
    "받다": "olmoq",
    "붙이다": "yopishtirmoq",
    "자다": "uxlamoq",
    "공부하다": "o'rganmoq",
    "일하다": "ishlamoq",
    "운동하다": "sport bilan shg'ullanmoq",
    "숙제를 하다": "uy vazifasini qilmoq",
    "옷을 사다": "kiyim sotib olmoq",
    "영화를 보다": "kino ko'rmoq",
    "친구를 만나다": "do'sti bilan uchrashmoq",
    "태권도를 배우다": "tekvondoni o'tganmoq",
    "밥을 먹다": "ovqat yemoq",
    "커피를 마시다": "kofe ichmoq",
    "책을 읽다": "kitob o'qimoq",
    "도서관": "kutubxona",
    "집": "uy",
    "백화점": "unvermag",
    "시장": "bozor",
    "공원": "park",
    "커피숍": "kafe",
    "극장": "kinoteatr",
    "학교": "maktab",
    "식당": "oshxona",
    "회사": "firma",
    "지금": "xozir",
    "하다": "qilmoq",
    "쉬다": "dam olmoq",
    "피자": "pitsa",
    "보다": "ko'rmoq",
    "사다": "sotib olmoq",
    "먹다": "yemoq",
    "마시다": "ichmoq",
    "읽다": "o'qimoq",
    "배우다": "o'rganmoq",
    "일본어": "yapon tili",
    "아르바이트하다": "qo'shimcha ish qilmoq",
    "요리": "ovqat pishirish",
    "만나다": "uchrashmoq",
    "오늘": "bugun",
    "그리고": "va",
    "어디": "qayer",
    "고기": "go'sht",
    "프랑스어": "fransuz tili",
    "드라마": "dramma",
    "그럼": "unday bo'lsa",
    "스포츠 센터": "sport markazi",
    "차": "choy",
    "가르치다": "o'qitmoq",
    "언어교육원": "til markazi",
    "불고기": "pulko'gi",
    "노래방": "karaoke",
    "공항": "aeroport",
    "우체국": "pochta",
    "대사관": "elchixona",
    "은행": "bank",
    "가게": "do'kon",
    "약국": "dorixona",
    "병원": "kasalxona",
    "미용실": "sartaroshxona",
    "앞": "oldi",
    "뒤": "orqasi",
    "옆": "yoni",
    "안": "ichi",
    "아래": "osti",
    "밑": "tagi",
    "위": "usti",
    "인사동": "insadong",
    "서울타워": "seul minorasi",
    "명동": "myongdong",
    "청계천": "chonkechon",
    "대학로": "seuldagi atraksion",
    "남산": "nam tog'i",
    "교실": "sinf xona",
    "찻집": "choyxona",
    "서울": "seul",
    "시내": "shahar markazi",
    "구경하다": "tomosha qilmoq",
    "쇼핑하다": "xarid qilmoq",
    "연극": "teatr",
    "알다": "bilmoq",
    "어머니": "ona",
    "아버지": "ota",
    "잘 지내다": "ishlari yaxshi bolmoq",
    "기숙사": "yotoqxona",
    "사진": "rasm",
    "매일": "har kuni",
    "그": "u",
    "반": "yarim",
    "사랑하다": "sevmoq",
    "서점": "kitob do'koni",
    "빵집": "novvoyxona",
    "화장실": "hojatxona",
    "음식": "ovqat",
    "가념품": "suviner",
    "그림": "rasm",
    "숫자": "raqam",
    "월요일": "dushanba",
    "화요일": "seshanba",
    "수요일": "chorshnba",
    "목요일": "payshanba",
    "금요일": "juma",
    "토요일": "shanba",
    "일요일": "yakshanba",
    "주말": "hafta oxiri",
    "날짜": "sana",
    "요일": "hafta kuni",
    "며칠": "qaysi kun",
    "시험": "imtxon",
    "언제": "qachon",
    "무슨": "qaysi",
    "생일": "tug'ulgan kun",
    "하고": "bilan",
    "크리스마스": "krismas",
    "파티": "bazm",
    "시간": "vaqt",
    "미안하다": "uzr so'ramoq",
    "약속": "vada",
    "같이": "birga",
    "어제": "qachon",
    "코엑스몰": "seuldagi savdo markazi",
    "카드": "karta",
    "선물": "sovg'a",
    "세수하다": "yuvinmoq",
    "이를 닦다": "tish yuvmoq",
    "거기": "u joy",
    "산책하다": "sayr qilmoq",
    "사진을 찍다": "rasmga olmoq",
    "누구": "kim",
    "혼자": "yolg'iz",
    "끝나다": "tugamoq",
    "강남역": "gangnam bekati",
    "그래서": "shuning uchun",
    "내일": "ertaga",
    "스케줄": "kun tartibi",
    "지난주": "o'tgan hafta",
    "양력": "quyosh kalendari",
    "음력": "oy kalendari",
    "설날": "yangi yil",
    "세배를 하다": "tazim qimoq",
    "떡국": "tokkuk",
    "샌드위치": "sendvich",
    "스파게티": "spagetti",
    "피자": "pitsa",
    "햄버거": "gamburger",
    "귤": "mandarin",
    "딸기": "qulupnay",
    "사과": "olma",
    "수박": "tarvuz",
    "앉다": "o'tirmoq",
    "주다": "bermoq",
    "잠깐만": "biroz",
    "기다리다": "kutmoq",
    "빵": "non",
    "몇": "qancha/necha",
    "아이스크림": "muzqaymoq",
    "주스": "sharbat",
    "녹차": "ko'k choy",
    "콜라": "kola",
    "메뉴": "menyu",
    "좋아하다": "yaxshi ko'rmoq",
    "우동": "udon taomi",
    "추석": "xosil bayrami",
    "차례를 지내다": "marosim o'tkazmoq",
    "송편": "guruchli pishiriq",
    "맥주": "pivo",
    "물건": "narsa",
    "개수": "sanoq",
    "그래요": "shunday",
    "여기요": "kechirasiz (birovni chaqirganda)",
    "맛있다": "mazali",
    "좋다": "yaxshi",
    "싸다": "arzon",
    "길": "yo'l",
    "복잡하다": "tiqilinch",
    "노래": "qo'shiq",
    "아리랑": "koreya folkor musiqasi",
    "바지": "shim",
    "운동화": "krossovka",
    "아저씨": "amaki",
    "모두": "hammasi",
    "또": "yana",
    "키위": "kivi",
    "파인애플": "ananas",   
    "박스": "quti",
    "멜론": "qovun",
    "과자": "pishiriq",
    "달걀": "tuxum",
    "휴지": "salfetka",
    "케이크": "tort",
    "아이스커피": "muzli kofe",
    "에스프레소": "espresso",
    "돈가스": "kotlet",
    "점심": "tushlik",
    "급": "daraja",
    "팔다": "sotmoq",
    "인치": "inch (o'lchov birlik)",
    "아주": "juda",
    "리모컨": "pult",
    "깨끗하다": "toza",
    "많다": "ko'p",
    "권": "kitoblarga –ta",
    "전화하다": "telefon qilmoq",
    "비싸다": "qimmat",
    "깎아 주다": "arzon qilmoq",
    "백김치": "oq kimchi",
    "깍두기": "rediskali kimchi",
    "오이김치": "bodring kimchi",
    "물김치": "suvli kimchi",
    "이런": "bunday",
    "김치볶음밥": "qovurilgan guruch",
    "김치전": "kimchi quymoq",
    "얼마": "qancha",
    "십 원": "10 von",
    "오십 원": "50 von",
    "백 원": "100 von",
    "오백 원": "500 von",
    "천 원": "1000 von",
    "오천 원": "5000 von",
    "만 원": "10.000 von",
    "오만 원": "50.000 von",
    "흐리다": "bulutli",
    "맑다": "havo ochiq",
    "덥다": "issiq",
    "춥다": "sovuq",
    "따뜻하다": "iliq",
    "시원하다": "salqin",
    "비가 오다": "yomg'ir yog'moq",
    "눈이 오다": "qor yog'moq",
    "계절": "fasl",
    "봄": "bahor",
    "여름": "yoz",
    "가을": "kuz",
    "겨울": "qish",
    "쉽다": "oson",
    "어렵다": "qiyin",
    "맵다": "achchiq",
    "가볍다": "yengil",
    "무겁다": "og'ir",
    "불규칙": "qoidaga tushmaslik",
    "날씨": "ob havo",
    "어때요?": "qanday?",
    "재미있다": "qiziqarli",
    "동생": "uka",
    "떡붂이": "tokpukki",
    "재미없다": "qiziq emas",
    "도쿄": "Tokyo",
    "조심해서 오세요": "ehtiyot bo’lib keling",
    "런던": "London",
    "싱가포르": "Singapur",
    "모스크바": "Moskva",
    "카이로": "Qohira",
    "시드니": "Sidney",
    "뉴욕": "Nyu York",
    "베이징": "Pekin",
    "어떻다": "qanday",
    "파리": "Parij",
    "요즘": "shu kunlarda",
    "쉬는 시간": "dam olish vaqti",
    "이야기하다": "suhbatlashmoq",
    "고향": "vatan",
    "스키장": "chang'i kompleksi",
    "단풍": "xazonrezgirlik",
    "수영장": "suzish kompleksi",
    "꽃": "gul",
    "바다": "dengiz",
    "생선": "baliqli taom",
    "부산": "Pusan",
    "질문": "savol",
    "작년": "o’tgan yili",
    "브라질": "Braziliya",
    "에서": "…dan",
    "브라질리아": "Brazilia",
    "항상": "doim",
    "처음": "ilk bor",
    "하늘": "osmon",
    "눈사람": "qor odam",
    "만들다": "tayyorlamoq",
    "필요하다": "zarur bo'moq",
    "놓다": "qo'ymoq",
    "각각": "har bir",
    "태국": "Tailand",
    "수영하다": "suzmoq",
    "망고": "mango",
    "선글라스": "ko'zoynak (quyosh)",
    "부채": "fen",
    "슬리퍼": "shippak/tapochka",
    "삼계탕": "samketang",
    "들": "…lar",
    "골프": "golf",
    "자전거": "velosiped",
    "게임": "o'yin",
    "테니스": "tennis",
    "농구": "basketbol",
    "피아노": "pianino",
    "당구": "billiard",
    "스키": "chang'i",
    "기타": "gitara",
    "스케이트": "skeyt",
    "축구": "futbol",
    "치다": "o'ynamoq, chalmoq",
    "타다": "minmoq/uchmoq",
    "하다": "qilmoq",
    "낮잠을 자다": "kunduzgi uyqu uxlamoq",
    "등산을 하다": "tog'ga chiqmoq",
    "산책을 하다": "sayr qilmoq",
    "여행을 하다": "sayohat qilmoq",
    "노래방에 가다": "karaokega bormoq",
    "찜질바에 가다": "saunaga bormoq",
    "걷다": "yurmoq",
    "버스": "avtobus",
    "걸어서 가다": "piyoda yurib bormoq",
    "음악": "musiqa",
    "듣다": "eshitmoq",
    "뉴스": "yangilik",
    "라디오": "radio",
    "잘": "yaxshi",
    "생활": "hayot",
    "조금": "biroz",
    "심심하다": "zerikarli",
    "한강": "Han daryosi",
    "그런데": "lekin",
    "어떻게": "qanday qilib",
    "가깝다": "yaqin",
    "관악산": "Gvanak tog’i",
    "시청": "shahar markazi",
    "정말": "haqiqatdan",
    "많다": "ko'p",
    "자주": "tez tez",
    "그래요": "shunday/rostdan",
    "다음": "kelasi",
    "피곤하다": "charchamoq",
    "크다": "katta",
    "식혜": "guruchli ichimlik",
    "저기": "anavi yer",
    "수업": "dars",
    "오후": "tushdan so'ng",
    "운동장": "sport maydoni",
    "번": "nomer",
    "보통": "odatda",
    "미팅": "uchrashuv",
    "소개하다": "tanishtirmoq",
    "소개팅": "tanishuv uchrashuvi",
    "웃어른": "katta odam",
    "선을 보다": "sovchilar orqali uchrashmoq",
    "할머니": "buva",
    "할아버지": "buvi",
    "어머니": "ona",
    "아버지": "ota",
    "누나": "opa(o’g’il bolalar uchun)",
    "형": "aka (o’g’il bolalarga)",
    "언니": "opa (qizlarga)",
    "오ppa": "aka(qizlarga)",
    "여동생": "singil",
    "남동생": "uka",
    "아내": "xotin",
    "남편": "er",
    "딸": "qiz farzand",
    "아들": "o’g’il farzand",
    "열": "10",
    "스물": "20",
    "서른": "30",
    "마흔": "40",
    "쉰": "50",
    "예순": "60",
    "일흔": "70",
    "여든": "80",
    "아흔": "90",
    "백": "100",
    "이름/성함": "ism",
    "집/댁": "uy",
    "사람/명/분": "odam",
    "나이/연세": "yosh",
    "있다/계시다": "bor bo’lmoq",
    "먹다/마시다/드시다": "yemoq",
    "자다/주무시다": "uxlamoq",
    "상자": "quti",
    "꺼내다": "sug’urmoq",
    "운전": "haydamoq",
    "수학": "matematika",
    "인사하다": "salomlashmoq",
    "이쪽": "bu",
    "한테서": "-dan",
    "뭘요": "unchalik emas",
    "동아리": "to’garak",
    "같은과": "o’xshash daraja",
    "윗사람": "o’zidan katta odam",
    "역사": "tarix",
    "이분": "bu kishi",
    "우리": "biz/bizning",
    "반친구": "xonadosh",
    "다니다": "qatnamoq",
    "친절하다": "mehribon",
    "사장님": "direktor",
    "전에": "oldin",
    "멋있다": "kelishgan",
    "부모님": "ota-ona",
    "미인": "chiroyli ayol",
    "대학교": "universitet",
    "신문사": "bosmaxona",
    "중학교": "o’rta maktab",
    "공손하다": "kamtar",
    "강아지": "kuchukcha",
    "가족사진": "oilaviy rasm",
    "웃다": "kulmoq",
    "취미": "hobby",
    "아기": "chaqaloq",
    "태어나다": "tug’ilmoq",
    "다른나라": "boshqa davlat",
    "되다": "bo’lmoq",
    "새벽": "sahar",
    "아침": "ertalab/nonushta",
    "낮": "kunduzi",
    "저녁": "kechki payt/ovqat",
    "밤": "tun",
    "오전": "obeddan oldin",
    "오후": "obeddan keyin",
    "일어나다": "uyg’onmoq/paydo bo'lmoq",
    "버스를 기다리다": "avtobus kutmoq",
    "운전하다": "mashina haydamoq",
    "버스를 타다": "avtobusga minmoq",
    "세수하다": "yuvinmoq",
    "청소하다": "uy tozalamoq",
    "회의하다": "majliz o’tkizmoq",
    "빨래하다": "kir yuvmoq",
    "전화하다": "telefon qilmoq",
    "컴퓨터를 하다": "kompyuterda ishlamoq",
    "요리하다": "ovqat pishirmoq",
    "샤워하다": "dush qabul qilmoq",
    "시": "soat",
    "분": "minut",
    "반": "yarim",
    "쯤": "taxminan",
    "수업을 하다": "dars qilmoq",
    "시험을 보다": "imtixon topshirmoq",
    "그리다": "rasm chizmoq",
    "이번": "bu safar",
    "방학": "ta’til",
    "조금후": "birozdan so’ng",
    "주말 잘 보내다": "dam olish kunini yaxshi o’tkazmoq",
    "데이트하다": "uchrashuvga chiqmoq",
    "박물관": "muzey",
    "연습": "mashq",
    "전통": "milliy",
    "이메일": "e-mail",
    "출입국관리사무소": "muhojirlar markazi",
    "그렇지만": "lekin",
    "머리": "bosh/soch",
    "목": "bo’yin",
    "어깨": "yelka",
    "팔": "qo’l",
    "손": "qo’l",
    "가슴": "ko’krak",
    "배": "qorin",
    "허리": "bel",
    "다리": "oyoq",
    "무릎": "tizza",
    "발": "oyoq",
    "눈": "ko’z",
    "코": "burun",
    "입": "og’iz",
    "귀": "quloq",
    "얼굴": "yuz/aft/bet",
    "기침을 하다": "yo’talmoq",
    "목이 아프다": "tomog’i og’rimoq",
    "열이 나다": "isitma chiqmoq",
    "콧물이 나다": "burun oqmoq",
    "바쁘da": "band bo’lmoq",
    "배고프다": "qorni ochmoq",
    "예쁘다": "chiroyli",
    "편지": "xat",
    "쓰다": "yozmoq/ishlatmoq/taqmoq/achchiq",
    "나쁘다": "yomon",
    "담배를 피우다": "sigaret chekmoq",
    "알겠다": "tushunarli",
    "늦다": "kechikmoq",
    "감기에 걸리다": "shamollamoq",
    "유행이다": "urf bo’lmoq",
    "약": "dori/taxminan",
    "푹 쉬다": "miriqib dam olmoq",
    "말(을) 하다": "gapirmoq",
    "오래": "uzoq vaqt",
    "목욕하다": "hammom qilmoq",
    "술": "aroq/ichimlik",
    "환자": "bemor",
    "의사": "doktor",
    "씻다": "yuvmoq",
    "따뜻한 물": "iliq suv",
    "얼음물": "muzli suv",
    "손님": "mehmon",
    "내년": "kelasi yil",
    "결혼하다": "turmush qurmoq",
    "괜찮다": "durust bo’lmoq",
    "다행이다": "hudoga shukur/yaxshiyamki",
    "나무/너무": "daraxt/juda",
    "무리하다": "ko'p ishlaganidan toliqmoq",
    "생신": "tug’ilgan kun (hurmat)",
    "리포트": "axborot bermoq",
    "내다": "topshirmoq",
    "알람": "budilnik",
    "끄다": "o’chirmoq",
    "걱정": "havotir",
    "발음": "talaffuz",
    "싸우다": "urishmoq",
    "금연": "chekish taqiqlanadi",
    "주차금지": "mashina qo’yish taqiqlanadi",
    "파": "piyoz",
    "붙이다": "yopishtirmoq",
    "소금물": "tuzli suv",
    "전화번호": "telefon raqam",
    "문자를 보내다": "sms jo’natmoq",
    "사무실": "ofis",
    "맛없다": "bemaza",
    "왜": "nimaga",
    "아까": "biroz oldin",
    "그럼요": "albatta",
    "이따": "keyinroq",
    "장소": "joy",
    "기차": "poyezd",
    "비행기": "samalyot",
    "배": "qayiq/kema/nok/qorin",
    "지하철": "metro",
    "자전거": "velosiped",
    "오토바이": "mototsikl",
    "타다": "minmoq",
    "내리다": "tushmoq",
    "닫다": "yopmoq",
    "돕다": "yordam bermoq",
    "칠판": "doska",
    "울다": "yig’lamoq",
    "쭉": "tog’riga",
    "세우다": "to’xtamoq/mashina qo'ymoq",
    "신호등": "svetofor",
    "편리하다": "qulay",
    "사용하다": "foydalanmoq",
    "요금": "to’lov",
    "깎다": "chegirma qilmoq/qirqmoq",
    "모자": "bosh kiyim",
    "바지": "shim",
    "치마": "yubka",
    "구두": "tufli",
    "운동화": "krasovka",
    "입다": "kiymoq (kiyim)",
    "신다": "kiymoq (poyabzal)",
    "크다": "katta",
    "작다": "kichkina",
    "길다": "uzun",
    "짧다": "kalta",
    "높다": "baland",
    "낮다": "past",
    "비싸다": "qimmat",
    "싸다": "arzon",
    "불편하다": "noqulay",
    "편하다": "qulay",
    "두껍다": "qalin",
    "얇다": "yupqa",
    "알다": "bilmoq",
    "만들다": "tayyorlamoq",
    "살다": "yashamoq",
    "놀다": "o’ynamoq",
    "팔다": "sotmoq",
    "열다": "ochmoq",
    "무섭다": "qo’rqinchli",
    "슬프다": "g’amgin",
    "키": "bo’y",
    "마음": "qalb",
    "선물하다": "sovg’a qilmoq",
    "보내다": "jo’natmoq",
    "드리다": "bermoq (hurmat)",
    "도시": "shahar",
    "한복": "koreya milliy libosi",
    "단순하다": "oddiy",
    "사탕": "shirinlik",
    "기쁘다": "hursand bo’lmoq",
    "먼저": "birinchi navbatta",
    "묻다": "so’ramoq",
    "도착하다": "yetib bormoq",
    "돌아오다": "qaytib kelmoq",
    "출발하다": "jo’nab ketmoq",
    "경치": "tabiat manzarasi",
    "반지": "uzuk",
    "떠나다": "tashlab ketmoq/jo'namoq",
    "즐겁다": "zavqli/hursand",
    "휴가": "ta’til",
    "박물관": "muzey",
    "준비하다": "tayyorlanmoq",
    "초대하다": "taklif qilmoq",
    "늦게": "kech",
    "빨리": "tez",
    "열심히": "yurakdan/qunt bilan",
    "일찍": "vaqtli/erta",
    "천천히": "sekin-sekin",
    "음료수": "salqin ichimlik",
    "세제": "poroshok/yuvish vositasi",
    "부자": "boy",
    "성명": "ism familya",
    "직업": "kasb",
    "종교": "din",
    "항상": "har doim",
    "자주": "tez-tez",
    "가끔": "ba’zan",
    "뵙다": "ko’rishmoq (hurmat)",
    "이유": "sabab",
    "국적": "millat",
    "평일": "ish kunlari",
    "소설책": "roman kitob",
    "문화": "madaniyat",
    "관심": "qiziqish",
    "발표하다": "doklad qilmoq",
    "친하다": "yaqin bo’lmoq",
    "비슷하다": "o’xshash",
    "규칙": "qoida",
    "사진을 찍다": "rasmga olmoq",
    "음악을 듣다": "musiqa eshitmoq",
    "낚시": "baliq ovi",
    "가입하다": "a’zo bo’lmoq",
    "모으다": "yig’moq",
    "모이다": "yig’ilmoq",
    "연극": "teatr",
    "축제": "festival",
    "불꽃놀이": "mushakbozlik",
    "아르바이트": "kunlik ish",
    "존경하다": "qadrlamoq/hurmat qilmoq",
    "출장": "kamandirovka",
    "기억이 남다": "xotirada qolmoq",
    "경험": "tajriba",
    "밝다": "yorug’/ochiq",
    "어둡다": "qorong’u/to’q",
    "환불하다": "pulini qaytarib olmoq",
    "필요하다": "kerak",
    "절약하다": "tejamoq",
    "주문하다": "buyurtma qilmoq",
    "싱싱하다": "jonli/yangi",
    "가격": "narx",
    "기간": "muddat",
    "일반석": "umumiy o’rindiq",
    "아마": "ehtimol",
    "느끼다": "xis qilmoq",
    "추천하다": "tavsiya qilmoq",
    "다양하다": "xar xil",
    "이용하다": "foydalanmoq",
    "봉투": "konvert/paket",
    "소포": "posilka",
    "신분증": "guvohnoma",
    "통장": "bank kitobchasi",
    "도장": "pechat",
    "벌써": "allaqachon",
    "잃어버리다": "yo’qotmoq",
    "전부": "hammasi",
    "신청하다": "ariza qilmoq",
    "사거리": "to’rt ko’cha",
    "육교": "ko’prik",
    "횡단보도": "piyodalar o’tish joyi",
    "건너다": "kesib o’tmoq",
    "근처": "yaqinida",
    "잊다": "unutmoq",
    "지나다": "o’tmoq",
    "창피하다": "uyalmoq",
    "속상하다": "hafa bo’lmoq",
    "답답하다": "siqilmoq",
    "긴장되다": "hayajonlanmoq",
    "화가 나다": "jahli chiqmoq",
    "짜증이 나다": "asabiylashmoq",
    "고장이 나다": "buzilmoq",
    "놓치다": "qo’ldan boy bermoq",
    "넘어지다": "yiqilib tushmoq",
    "졸다": "mudramoq",
    "외우da": "yodlamoq",
    "당황하다": "hayron qolmoq",
    "표현하다": "ifodalamoq",
    "설명하다": "tushuntirmoq",
    "무료": "tekin",
    "궁금하다": "qiziqmoq/tashvishlanmoq",
    "갑자기": "to’satdan",
    "통역하다": "og’zaki tarjima qilmoq",
    "정보": "ma’lumot",
    "달다": "shirin",
    "짜다": "sho’r",
    "시다": "nordon",
    "맵다": "achchiq",
    "동갑": "tengdosh",
    "미리": "oldindan",
    "시키다": "buyurtirmoq",
    "배달되다": "yetkazib bermoq",
    "직원": "ishchi",
    "토하다": "ko’ngli aynimoq",
    "어지럽다": "boshi aylanmoq",
    "내과": "ichki kasalliklar",
    "치과": "tish kasalliklari",
    "낫다": "yaxshilanmoq/tuzalmoq",
    "붓다": "ishmoq",
    "짓다": "qurmoq/ism qo'ymoq",
    "젓다": "aralashtirmoq",
    "화해하다": "yarashmoq",
    "고민": "tashvish",
    "조언": "maslahat",
    "습관": "odat",
    "예방하다": "oldini olmoq",
    "활발하다": "harakatchan",
    "내성적이다": "passiv/uyatchan",
    "꼼꼼하다": "extiyotkor/sinchkov",
    "똑똑하다": "aqlli",
    "날씬하다": "ozg’in",
    "정확하다": "aniq",
    "외모": "ko’rinishi",
    "정리하다": "tartibga keltirmoq",
    "기숙사": "yotoqxona",
    "부엌": "oshxona",
    "현관": "ostona/kirish",
    "전망": "ko’rinishi (vid)",
    "부동산": "ko’chmas mulk",
    "구하다": "qidirmoq",
    "계약": "shartnoma",
    "실수하다": "xato qilmoq",
    "물론이다": "albatta",
    "예절": "odob axloq",
    "칭찬하다": "maqtamoq",
    "은퇴하다": "nafaqaga chiqmoq",
    "발전하다": "rivojlanmoq",
    "익숙하다": "moslashmoq",
    "변화": "o’zgarish",
    "세배를 하다": "tazim qilmoq",
    "나누다": "bo’lmoq/ulashmoq",
    "소원을 빌다": "tilak tilamoq",
    "부딪히다": "to’qnashib ketmoq",
    "모시다": "olib bormoq (hurmat)",
    "정신이 없다": "xayoli joyida emas",
    "서다": "tik turmoq",
    "소중하다": "qadrli",
    "그립다": "sog’inmoq",
    "아쉽다": "achinmoq/afsuslanmoq",
    "후회가 되다": "afsuslanmoq",
    "단풍": "xazonrezgi/rangli barglar",
    "성적": "baho/daraja",
    "합격하다": "imtihondan o’tmoq",
    "참석하다": "qatnashmoq",
    "도움이 되다": "yordam bo’lmoq",
    "게다가": "ustiga ustak",
    "성공하다": "omadli/muvaffaqiyat qozonmoq",
    "미루다": "kechiiktirmoq",
    "부지런하다": "ishchan/mehnatkash",
    "안개": "tuman",
    "번개": "chaqmoq",
    "천둥": "momaqaldiroq",
    "부서지다": "sinib tushmoq",
    "무너지다": "qulamoq",
    "살을 빼다": "ozmoq",
    "굵다": "yo'g'on/katta",
    "반드시": "albatta",
    "다듬다": "tozalash/tekkislash",
    "썰다": "to'g'ramoq",
    "볶다": "qovurmoq",
    "삶다": "qaynatib pishirmoq",
    "익다": "pishmoq (meva/ovqat)",
    "부럽다": "havas qilmoq",
    "감사합니다": "Raxmat / Tashakkur",
    "죄송합니다": "Kechirasiz / Uzr",
    "천만에요": "Arzimaydi",
    "환영합니다": "Xush kelibsiz",
    "출발": "Jo'nab ketish",
    "도착": "Yetib kelish",
    "비상구": "Zudlik bilan chiqish yo'li",
    "금지": "Taqiqlangan"
}

uz_ko = {
    "maktab": "학교",
"uy": "집",
"avtomobil": "자동차",
"samolyot": "비행기",
"truk": "트럭",
"mototsikl": "오토바이",
"velosiped": "자전거",
"kursi": "의자",
"stol": "식탁",
"parta": "책상",
"oddiy": "옷",
"besh": "오",
"ikki": "이",
"bu": "이",
"tish": "이",
"bola": "아이",
"bodiring": "오이",
"qo'shiqchi": "가수",
"go'sht": "고기",
"tufli": "구두",
"davlat": "나라",
"daraxt": "나무",
"oyoq": "다리",
"radio": "라디오",
"bosh": "머리",
"banan": "바나나",
"shim": "바지",
"sigir": "소",
"chaqaloq": "아기",
"ona": "어머니",
"xarita": "지도",
"bosh kiyim": "모자",
"ota": "아버지",
"bel": "허리",
"yer osti": "지하",
"beyzbol": "야구",
"palma": "야자수",
"suxbat": "이야기",
"ayol": "여자",
"suyak": "뼈",
"til": "혀",
"yo'ga": "요가",
"ovqat pishirish": "요리",
"tualet qog'ozi": "휴지",
"sut": "우유",
"karta": "카드",
"burun": "코",
"balandlik": "키",
"tuyaqush": "타조",
"pomidor": "토마토",
"motodor": "투우수",
"pashsha": "파리",
"uzum": "포도",
"pochta markasi": "우표",
"choy": "차",
"yubka": "치마",
"qalampir": "고추",
"kofe": "커피",
"palto": "코트",
"poyezd bileti": "기차표",
"zog'cha": "까치",
"dum": "꼬리",
"fil": "코끼리",
"uzmoq": "따다",
"suzmoq": "뜨다",
"ildiz": "뿌리",
"arzon": "싸다",
"yozmoq": "쓰다",
"sho'r": "짜다",
"bug'lamoq": "찌다",
"qalbaki": "가짜",
"chumoli": "개미",
"qayiq": "배",
"qush": "새",
"quyosh": "해",
"qisqichbaqa": "게",
"yuvinish": "세수",
"arg'imchoq": "그네",
"kamera": "카메라",
"chiroyli": "예쁘다",
"xattotlik": "서예",
"soat": "시계",
"pishiriq": "과자",
"ko'ylak": "와이셔츠",
"olma": "사과",
"nima": "뭐",
"issiq": "더워요",
"sovuq": "추워요",
"cho'chqa": "돼지",
"nimaga": "왜",
"svitr": "스웨터",
"yodlamoq": "외우다",
"firma": "회사",
"miya": "뚜뇌",
"quloq": "귀",
"dam olmoq": "쉬다",
"sichqon": "쥐",
"qaychi": "가위",
"doktor": "의사",
"majlis": "회의",
"tarvuz": "수박",
"kitob": "책",
"pul": "돈",
"gazeta": "신문",
"zontik": "우산",
"gul": "꽃",
"suv": "물",
"erkak": "남자",
"kompyuter": "컴퓨터",
"og'iz": "입",
"tizza": "무릎",
"o'rmon": "숲",
"sumka": "가방",
"Xitoy": "중국",
"Yaponiya": "일본",
"AQSH": "미국",
"Koreya": "한국",
"fransiya": "프랑스",
"Germaniya": "독일",
"avstraliya": "호주",
"Angliya": "영국",
"bo'sh joy": "빈칸",
"mos": "알맞다",
"so'z": "단어",
"o'qituvchi": "선생님",
"o'quvchi": "학생",
"firma ishchisi": "회사원",
"oshpaz": "요리사",
"muxbir": "기자",
"askar": "군인",
"salomlashish gapi": "인사말",
"uchrashmoq": "만나다",
"xursand bo'lmoq": "반갑다",
"koreys tili": "한국말",
"surat": "그림",
"suxbatlashmoq": "이야기하다",
"men": "저",
"anavi": "저",
"janob": "씨",
"xonim": "씨",
"ha": "네",
"uy bekasi": "주부",
"gapirish": "말하기",
"qaysi": "어느",
"Kanada": "캐나다",
"millat": "국적",
"so'ramoq": "묻다",
"Xindiston": "인도",
"kasb": "직업",
"yo'q": "아니요",
"sizlar": "여러분",
"Rossiya": "러시아",
"Pokiston": "파키스탄",
"do'st": "친구",
"ism karta": "명함",
"ism": "이름",
"telefon raqam": "전화번호",
"ingiliz tili": "영어",
"internetdagi blog": "블로그",
"qidirmoq": "찾다",
"madaniyat": "문화",
"daftar": "공책",
"ruchka": "볼펜",
"o'chirg'ich": "지우개",
"soyabon": "우산",
"lug'at": "사전",
"ko'zoynak": "안경",
"telefon": "휴대폰",
"tanga": "동전",
"mashina": "차",
"qiz o'rtoq": "여자 친구",
"penal": "필통",
"qalamdon": "필통",
"elektron lug'at": "전자사전",
"koreys tilida": "한국어로",
"chizg'ich": "자",
"jurnal": "잡지",
"hamyon": "지갑",
"marhamat": "여기 있어요",
"iltimos": "좀",
"ko'la": "콜라",
"sharbat": "주스",
"transport kartasi": "교통카드",
"salfetka": "휴지",
"xush kelibsiz": "어서 오세요",
"apelsin": "오랜지",
"kino": "영화",
"televizor": "텔레비전",
"non": "방",
"Seul universiteti": "서울대학교",
"mening": "제",
"kravat": "침대",
"xonadosh": "룸메이트",
"konditsioner": "에어컨",
"narsa": "물건",
"jamoa": "팀",
"bo'lishmoq": "나누다",
"olmoq": "받다",
"yopishtirmoq": "붙이다",
"uxlamoq": "자다",
"o'rganmoq": "공부하다",
"ishlamoq": "일하다",
"sport bilan shug'ullanmoq": "운동하다",
"uy vazifasini qilmoq": "숙제를 하다",
"kiyim sotib olmoq": "옷을 사다",
"kino ko'rmoq": "영화를 보다",
"do'sti bilan uchrashmoq": "친구를 만나다",
"ovqat yemoq": "밥을 먹다",
"kofe ichmoq": "커피를 마시다",
"kitob o'qimoq": "책을 읽다",
"kutubxona": "도서관",
"univermag": "백화점",
"bozor": "시장",
"park": "공원",
"kafe": "커피숍",
"kinoteatr": "극장",
"oshxona": "식당",
"xozir": "지금",
"qilmoq": "하다",
"pitsa": "피자",
"ko'rmoq": "보다",
"sotib olmoq": "사다",
"yemoq": "먹다",
"ichmoq": "마시다",
"o'qimoq": "읽다",
"yapon tili": "일본어",
"qo'shimcha ish qilmoq": "아르바이트하다",
"bugun": "오늘",
"va": "그리고",
"qayer": "어디",
"go'sht": "고기",
"fransuz tili": "프랑스어",
"dramma": "드라마",
"unday bo'lsa": "그럼",
"sport markazi": "스포츠 센터",
"o'qitmoq": "가르치다",
"til markazi": "언어교육원",
"pulko'gi": "불고기",
"karaoke": "노래방",
"aeroport": "공항",
"pochta": "우체국",
"elchixona": "대사관",
"bank": "은행",
"do'kon": "가게",
"dorixona": "약국",
"kasalxona": "병원",
"sartaroshxona": "미용실",
"oldi": "앞",
"orqasi": "뒤",
"yoni": "옆",
"ichi": "안",
"osti": "아래",
"tagi": "밑",
"insadong": "인사동",
"seul minorasi": "서울타워",
"myongdong": "명동",
"chonkechon": "청계천",
"seuldagi atraksion": "대학로",
"nam tog'i": "남산",
"sinf xona": "교실",
"choyxona": "찻집",
"seul": "서울",
"shahar markazi": "시내",
"tomosha qilmoq": "구경하다",
"xarid qilmoq": "쇼핑하다",
"teatr": "연극",
"bilmoq": "알다",
"ishlari yaxshi bo'lmoq": "잘 지내다",
"yotoqxona": "기숙사",
"rasm": "사진",
"har kuni": "매일",
"u": "그",
"yarim": "반",
"sevmoq": "사랑하다",
"kitob do'koni": "서점",
"novvoyxona": "빵집",
"hojatxona": "화장실",
"ovqat": "음식",
"suviner": "기념품",
"raqam": "숫자",
"dushanba": "월요일",
"seshanba": "화요일",
"chorshanba": "수요일",
"payshanba": "목요일",
"juma": "금요일",
"shanba": "토요일",
"yakshanba": "일요일",
"hafta oxiri": "주말",
"sana": "날짜",
"hafta kuni": "요일",
"qaysi kun": "며칠",
"imtxon": "시험",
"qachon": "언제",
"qaysi": "무슨",
"tug'ilgan kun": "생일",
"bilan": "하고",
"krismas": "크리스마스",
"bazm": "파티",
"vaqt": "시간",
"uzr so'ramoq": "미안하다",
"vada": "약속",
"birga": "같이",
"kecha": "어제",
"seuldagi savdo markazi": "코엑스몰",
"sovg'a": "선물",
"yuvinmoq": "세수하다",
"tish yuvmoq": "이를 닦다",
"u joy": "거기",
"sayr qilmoq": "산책하다",
"rasmga olmoq": "사진을 찍다",
"kim": "누구",
"yolg'iz": "혼자",
"tugamoq": "끝나다",
"gangnam bekati": "강남역",
"shuning uchun": "그래서",
"ertaga": "내일",
"kun tartibi": "스케줄",
"o'tgan hafta": "지난주",
"quyosh kalendari": "양력",
"oy kalendari": "음력",
"yangi yil": "설날",
"tazim qilmoq": "세배를 하다",
"tokkuk": "떡국",
"xosil bayrami": "추석",
"marosim o'tkazmoq": "차례를 지내다",
"guruchli pishiriq": "송편",
  "sendvich": "샌드위치",
  "spagetti": "스파게티",
  "pitsa": "피자",
  "gamburger": "햄버거",
  "mandarin": "귤",
  "qulupnay": "딸기",
  "olma": "사과",
  "tarvuz": "수박",
  "o'tirmoq": "앉다",
  "bermoq": "주다",
  "biroz": "잠깐만",
  "kutmoq": "기다리다",
  "non": "빵",
  "qancha/necha": "몇",
  "muzqaymoq": "아이스크림",
  "sharbat": "주스",
  "ko'k choy": "녹차",
  "kola": "콜라",
  "menyu": "메뉴",
  "yaxshi ko'rmoq": "좋아하다",
  "udon taomi": "우동",
  "xosil bayrami": "추석",
  "marosim o'tkazmoq": "차례를 지내다",
  "guruchli pishiriq": "송편",
  "uy": "집",
  "avtomobil": "자동차",
  "samolyot": "비행기",
  "truk": "트럭",
  "mototsikl": "오토바이",
  "pivo": "맥주",
  "narsa": "물건",
  "sanoq": "개수",
  "shunday": "그래요",
  "kechirasiz (birovni chaqirganda)": "여기요",
  "mazali": "맛있다",
  "yaxshi": "좋다",
  "arzon": "싸다",
  "yo'l": "길",
  "tiqilinch": "복잡하다",
  "qo'shiq": "노래",
  "koreya folkor musiqasi": "아리랑",
  "shim": "바지",
  "krossovka": "운동화",
  "amaki": "아저씨",
  "hammasi": "모두",
  "yana": "또",
  "kivi": "키위",
  "ananas": "파인애플",
  "quti": "박스",
  "qovun": "멜론",
  "pishiriq": "과자",
  "tuxum": "달걀",
  "salfetka": "휴지",
  "tort": "케이크",
  "muzli kofe": "아이스커피",
  "espresso": "에스프레소",
  "kotlet": "돈가스",
  "tushlik": "점심",
  "daraja": "급",
  "sotmoq": "팔다",
  "inch (o'lchov birlik)": "인치",
  "juda": "아주",
  "pult": "리모컨",
  "toza": "깨끗하다",
  "ko'p": "많다",
  "kitoblarga –ta": "권",
  "telefon qilmoq": "전화하다",
  "qimmat": "비싸다",
  "arzon qilmoq": "깎아 주다",
  "oq kimchi": "백김치",
  "rediskali kimchi": "깍두기",
  "bodring kimchi": "오이김치",
  "suvli kimchi": "물김치",
  "bunday": "이런",
  "qovurilgan guruch": "김치볶음밥",
  "kimchi quymoq": "김치전",
  "qancha": "얼마",
  "10 von": "십 원",
  "50 von": "오십 원",
  "100 von": "백 원",
  "baliqli taom": "생선",
  "Pusan": "부산",
  "savol": "질문",
  "o’tgan yili": "작년",
  "Braziliya": "브라질",
  "…dan": "에서",
  "Brazilia": "브라질리아",
  "doim": "항상",
  "ilk bor": "처음",
  "osmon": "하늘",
  "qor odam": "눈사람",
  "tayyorlamoq": "만들다",
  "zarur bo'moq": "필요하다",
  "qo'ymoq": "놓다",
  "har bir": "각각",
  "Tailand": "태국",
  "suzmoq": "수영하다",
  "mango": "망고",
  "ko'zoynak (quyosh)": "선글라스",
  "fen": "부채",
  "shippak/tapochka": "슬리퍼",
  "samketang": "삼계탕",
  "…lar": "들",
  "8 과": "8 과",
  "golf": "골프",
  "velosiped": "자전거",
  "o'yin": "게임",
  "tennis": "테니스",
  "basketbol": "농구",
  "pianino": "피아노",
  "billiard": "당구",
  "chang'i": "스키",
  "gitara": "기타",
  "skeyt": "스케이트",
  "futbol": "축구",
  "o'ynamoq, chalmoq": "치다",
  "minmoq/uchmoq": "타다",
  "qilmoq": "하다",
  "kunduzgi uyqu uxlamoq": "낮잠을 자다",
  "tog'ga chiqmoq": "등산을 하다",
  "sayr qilmoq": "산책을 하다",
  "sayohat qilmoq": "여행을 하다",
  "karaokega bormoq": "노래방에 가다",
  "saunaga bormoq": "찜질바에 가다",
  "yurmoq": "걷다",
  "avtobus": "버스",
  "piyoda yurib bormoq": "걸어서 가다",
  "musiqa": "음악",
  "eshitmoq": "듣다",
  "yangilik": "뉴스",
  "radio": "라디오",
  "yaxshi": "잘",
  "hayot": "생활",
  "biroz": "조금",
  "zerikarli": "심심하다",
  "Han daryosi": "한강",
  "lekin": "그런데",
  "qanday qilib": "어떻게",
  "yaqin": "가깝다",
  "Gvanak tog’i": "관악산",
  "shahar markazi": "시청",
  "haqiqatdan": "정말",
  "ko'p": "많다",
  "tez tez": "자주",
  "shunday/rostdan": "그래요",
  "kelasi": "다음",
  "charchamoq": "피곤하다",
  "katta": "크다",
  "guruchli ichimlik": "식혜",
  "anavi yer": "저기",
  "dars": "수업",
  "tushdan so'ng": "오후",
  "sport maydoni": "운동장",
  "nomer": "번",
  "odatda": "보통",
  "uchrashuv": "미팅",
  "tanishtirmoq": "소개하다",
  "tanishuv uchrashuvi": "소개팅",
  "katta odam": "웃어른",
  "sovchilar orqali uchrashmoq": "선을 보다",
    "buva": "할머니",
    "buvi": "할아버지",
    "ona": "어머니",
    "ota": "아버지",
    "opa (o’g’il bolalar uchun)": "누나",
    "aka (o’g’il bolalarga)": "형/aka",
    "opa (qizlarga)": "언니",
    "aka (qizlarga)": "오빠",
    "singil": "여동생",
    "uka": "남동생",
    "xotin": "아내",
    "er": "남편",
    "qiz farzand": "딸",
    "o’g’il farzand": "아들",
    "10": "열",
    "20": "스물",
    "30": "서른",
    "40": "마흔",
    "50": "쉰",
    "60": "예순",
    "70": "일흔",
    "80": "여든",
    "90": "아흔",
    "100": "백",
    "ism": "이름/성함",
    "uy": "집/댁",
    "odam": "사람/명/분",
    "yosh": "나이/연세",
    "bor bo’lmoq": "있다/계시다",
    "yemoq/ichmoq": "먹다/마시다/드시다",
    "uxlamoq": "자다/주무시다",
    "quti": "상자",
    "sug’urmoq": "꺼내다",
    "haydamoq": "운전/운전하다",
    "matematika": "수학",
    "salomlashmoq": "인사하다",
    "bu": "이쪽/bu",
    "-dan": "한테서",
    "unchalik emas": "뭘요",
    "to’garak": "동아리",
    "o’xshash daraja": "같은과",
    "o’zidan katta odam": "윗사람",
    "tarix": "역사",
    "bu kishi": "이분",
    "biz/bizning": "우리",
    "xonadosh": "반친구",
    "qatnamoq": "다니다",
    "mehribon": "친절하다",
    "direktor": "사장님/감독",
    "oldin": "전에/예전에",
    "kelishgan": "멋있다",
    "ota-ona": "부모님",
    "chiroyli ayol": "미인",
    "universitet": "대학교",
    "bosmaxona": "신문사",
    "o’rta maktab": "중학교",
    "kamtar": "공손하다",
    "kuchukcha": "강아지",
    "oilaviy rasm": "가족사진",
    "kulmoq": "웃다",
    "hobby": "취미",
    "chaqaloq": "아기/유아",
    "tug’ilmoq": "태어나다",
    "boshqa davlat": "다른나라",
    "bo’lmoq": "되다",
    "sahar": "새벽",
    "ertalab": "아침",
    "kunduzi": "낮",
    "kechki payt": "저녁",
    "tun": "밤",
    "tushdan oldin": "오전",
    "tushdan keyin": "오후",
    "uyg’onmoq": "일어나다",
    "avtobus kutmoq": "버스를 기다리다",
    "avtobusga minmoq": "버스를 타다",
    "yuvinmoq": "세수하다",
    "uy tozalamoq": "청소하다",
    "majliz o’tkizmoq": "회의하다",
    "kir yuvmoq": "빨래하다",
    "telefon qilmoq": "전화하다/전화를 걸다",
    "kompyuterda ishlamoq": "컴퓨터를 하다",
    "ovqat pishirmoq": "요리하다",
    "dush qabul qilmoq": "샤워하다",
    "soat": "시",
    "minut": "분",
    "yarim": "반",
    "taxminan": "쯤/약",
    "dars qilmoq": "수업을 하다",
    "imtixon topshirmoq": "시험을 보다",
    "rasm chizmoq": "그리다/그림을 그리다",
    "ta’til": "방학/휴가",
    "birozdan so’ng": "조금후",
    "muzey": "박물관",
    "mashq": "연습",
    "milliy": "전통/전통적",
    "muhojirlar markazi": "출입국관리사무소",
    "lekin": "그렇지만/그러나",
    "bosh": "머리",
    "bo’yin": "목",
    "yelka": "어깨",
    "qo’l": "팔/손",
    "ko’krak": "가슴",
    "qorin": "배",
    "bel": "허리",
    "oyoq": "다리/발",
    "tizza": "무릎",
    "ko’z": "눈",
    "burun": "코",
    "og’iz": "입",
    "quloq": "귀",
    "yuz": "얼굴",
    "yo’talmoq": "기침을 하다",
    "isitma chiqmoq": "열이 나다",
    "burun oqmoq": "콧물이 나다",
    "band bo’lmoq": "바쁘다",
    "qorni ochmoq": "배고프다/출출하다",
    "chiroyli": "예쁘다",
    "xat": "편지",
    "yozmoq": "쓰다/적다",
    "yomon": "나쁘다",
    "sigaret chekmoq": "담배를 피우다",
    "tushunarli": "알겠다",
    "kechikmoq": "늦다",
    "shamollamoq": "감기에 걸리다",
    "urf bo’lmoq": "유행이다",
    "dori": "약",
    "gapirmoq": "말(을) 하다/말씀하다",
    "uzoq vaqt": "오래/한참",
    "hammom qilmoq": "목욕하다",
    "aroq": "술",
    "bemor": "환자",
    "doktor": "의사",
    "yuvmoq": "씻다/닦다",
    "mehmon": "손님",
    "turmush qurmoq": "결혼하다",
    "hudoga shukur": "다행이다",
    "juda": "너무/아주/매우",
    "topshirmoq": "내다/제출하다",
    "havotir": "걱정/고민",
    "talaffuz": "발음",
    "urishmoq": "싸우다",
    "tuzli suv": "소금물",
    "telefon raqam": "전화번호",
    "poyezd": "기차",
    "samalyot": "비행기",
    "metro": "지하철",
    "velosiped": "자전거",
    "mototsikl": "오토바이",
    "minmoq": "타다",
    "tushmoq": "내리다",
    "yopmoq": "닫다",
    "yordam bermoq": "돕다/도움이 되다",
    "doska": "칠판",
    "yig’lamoq": "울다",
    "to’g’riga": "쭉/직진하다",
    "svetofor": "신호등",
    "qulay": "편리하다/편하다",
    "foydalanmoq": "사용하다/이용하다",
    "to’lov": "요금/비용",
    "bosh kiyim": "모자",
    "shim": "바지",
    "yubka": "치마",
    "tufli": "구두",
    "krasovka": "운동화",
    "kiymoq": "입다/신다/쓰다/끼다",
    "katta": "크다",
    "kichkina": "작다",
    "uzun": "길다",
    "kalta": "짧다",
    "baland": "높다",
    "past": "낮다",
    "qimmat": "비싸다",
    "arzon": "싸다",
    "qalin": "두껍다",
    "yupqa": "얇다",
    "bilmoq": "알다",
    "tayyorlamoq": "만들다/준비하다",
    "yashamoq": "살다",
    "o’ynamoq": "놀다",
    "sotmoq": "팔다",
    "ochmoq": "열다",
    "qo’rqinchli": "무섭다",
    "g’amgin": "슬프da",
    "bo’y": "키",
    "qalb": "마음",
    "sovg’a qilmoq": "선물하다",
    "shahar": "도시",
    "hursand bo’lmoq": "기쁘다/즐겁다",
    "so’ramoq": "묻다/질문하다/여쭈다",
    "yetib bormoq": "도착하다",
    "qaytib kelmoq": "돌아오다",
    "tez": "빨리/서두르다",
    "yurakdan": "열심히",
    "vaqtli": "일찍",
    "sekin": "천천히",
    "salqin ichimlik": "음료수",
    "boy": "부자",
    "kasb": "직업",
    "din": "종교",
    "har doim": "항상/매일",
    "tez-tez": "자주",
    "ba’zan": "가끔",
    "millat": "국적",
    "madaniyat": "문화",
    "qiziqish": "관심/취미",
    "yaqin bo’lmoq": "친하다",
    "o’xshash": "비슷하다",
    "qoida": "규칙",
    "teatr": "연극",
    "festival": "축제",
    "kunlik ish": "아르바이트",
    "tajriba": "경험/체험",
    "yorug’": "밝다",
    "qorong’u": "어둡다",
    "tejamoq": "절약하다",
    "yangi": "싱싱하다/새롭다/새",
    "narx": "가격/값",
    "muddat": "기간",
    "ehtimol": "아마",
    "posilka": "소포/택배",
    "allaqachon": "벌써",
    "yo’qotmoq": "잃어버리다/놓치da",
    "hammasi": "전부/다/모든",
    "ariza qilmoq": "신청하다",
    "ko’prik": "육교",
    "unutmoq": "잊다",
    "uyalmoq": "창피하다",
    "jahli chiqmoq": "화가 나다",
    "asabiylashmoq": "짜증이 나다",
    "buzilmoq": "고장이 나다",
    "yiqilib tushmoq": "넘어지다/쓰러지da",
    "mudramoq": "졸다",
    "yodlamoq": "외우da",
    "tushuntirmoq": "설명하다",
    "tekin": "무료",
    "to’satdan": "갑자기",
    "ma’lumot": "정보/소식",
    "shirin": "달다",
    "sho’r": "짜다",
    "nordon": "시다",
    "achchiq": "맵다",
    "tengdosh": "동갑",
    "oldindan": "미리",
    "buyurtirmoq": "시키다/주문하다",
    "ishchi": "직원",
    "qurmoq": "짓다",
    "aralashtirmoq": "젓다/섞다",
    "yarashmoq": "화해하다/어울리다",
    "maslahat": "조언",
    "odat": "습관/버릇",
    "aqlli": "똑똑하다",
    "ozg’in": "날씬하다/마르다",
    "aniq": "정확하다",
    "tartibga keltirmoq": "정리하다",
    "yotoqxona": "기숙사/고시원",
    "oshxona": "부엌",
    "qidirmoq": "구하다",
    "shartnoma": "계약",
    "albatta": "물론이다/반드시/꼭",
    "odob axloq": "예절",
    "maqtamoq": "칭찬하다",
    "o’zgarish": "변화",
    "bo’lmoq/ulashmoq": "나누다",
    "tilak tilamoq": "소원을 빌da",
    "tik turmoq": "서다",
    "qadrli": "소중하다",
    "sog’inmoq": "그립da",
    "imtihondan o’tmoq": "합격하다",
    "yordam bo’lmoq": "도움이 되다",
    "muvaffaqiyat qozonmoq": "성공하다",
    "tuman": "안개",
    "chaqmoq": "번개",
    "momaqaldiroq": "천둥",
    "sinib tushmoq": "부서지da",
    "qulamoq": "무너지da",
    "ozmoq": "살을 빼da",
    "yo'g'on": "굵다",
    "to’g’ramoq": "썰다",
    "qovurmoq": "볶다",
    "pishmoq": "익다",
    "havas qilmoq": "부럽다",
    "go'sht": "고기",
    "davlat": "나라",
    "daraxt": "나무",
    "poyabzal": "신발",
    "tashxis olmoq": "진료를 받다",
    "xursand": "기쁘다/즐겁다",
    "g'amgin": "슬프다/속상하다",
    "stressni yechmoq": "스트레스를 풀다",
    "foydalanmoq": "이용하다/사용하다",
    "shovqin": "시끄럽다",
    "havo": "공기",
    "qaror qilmoq": "결정하다",
    "shart": "조건",
    "tazim qilmoq": "세배를 하다",
    "bayram": "명절",
    "tayyorlamoq": "차리다/준비하다",
    "ko'rsatib bermoq": "보여 주다",
    "xotira": "추억/기억",
    "ajdodlar": "조상",
    "namlik": "습도",
    "muzlamoq": "얼다",
    "qor yog'moq": "눈이 내리다",
    "yurtiga bormoq": "고향에 가다",
    "shaxsiy ish": "사정",
    "qobiliyat": "실력",
    "imtihon": "시험",
    "stipendiya": "장학금",
    "talaba": "학생",
    "ma'ruza": "강의/수강",
    "jamiyat": "사회",
    "axlat": "쓰레기",
    "qaytarmoq": "따라하다",
    "jamiat hayoti": "사회생활",
    "pichirlamoq": "귓속말",
    "tishlamoq": "깨물다",
    "xurrak otmoq": "코를 골다",
    "alaxsiramoq": "잠꼬대를 하다",
    "shikoyat": "불평",
    "javramoq": "잔소리",
    "voz kechmoq": "포기하다",
    "yordamchi": "조교",
    "mutlaqo": "절대로",
    "qochib ketmoq": "도망가다",
    "omadsizlik": "실패",
    "mansab/hokimiyat": "권력",
    "masalan": "예를 들면",
    "chunki": "왜냐하면",
    "danngasa": "게으르다",
    "jala": "소나기",
    "sel": "폭우",
    "toshqin": "홍수",
    "qurg'oqchilik": "가뭄",
    "tadbirkorlik": "사업",
    "turist": "관광객",
    "to'xtamoq (yomg'ir)": "그치다",
    "akvarium": "수족관",
    "qum": "모래",
    "alohida": "따ro",
    "qattiq": "꽁꽁",
    "shakar": "설탕",
    "sarimsoq": "마늘",
    "kunjut": "깨",
    "kunjut yog'i": "참기름",
    "murch": "후추",
    "tekkislamoq": "다듬다",
    "ezmoq/maydalamoq": "다지다",
    "bug'da pishirmoq": "찌다",
    "qovurmoq (yog'da)": "튀기다",
    "bo'yamoq": "칠하다/염색하다",
    "tashqari": "밖",
    "zina/yo'lak": "복도",
    "tovada pishirmoq": "부치다",
    "enngil taom": "간식",
    "asal": "꿀",
    "o'ramoq": "싸다/하다",
    "botirmoq (sousga)": "찍다",
    "suvi (ovqat)": "해장국",
    "havas qilmoq": "부럽다",
    "qisqichbaqa": "새우",
    "un": "밀가루",
    "rahmat": "감사합니다",
    "kechirim": "죄송합니다",
    "arzimaydi": "천만에요",
    "chiqish": "출구",
    "kirish": "입구",
    "to'xtash": "정지"
}

@bot.message_handler(commands=['start'])
def start(message):
    bot.send_message(
        message.chat.id,
        "🇰🇷 Koreyscha ↔ 🇺🇿 O‘zbekcha lug‘at bot\n\n"
        "So‘z yozing:\n"
        "집 → uy\n",
        "자동차 → avtomobil\n",
        "비행기 → samolyot\n",
        "트럭 → truk\n",
        "오토바이 → mototsikl\n",
        "자전거 → velosiped\n",
        "의자 → kursi\n",
        "식탁 → stol\n",
        "책상 → parta\n",
        "옷 → kiyim\n",
        "오 → besh\n",
        "이 → bu / ikki / tish\n",
        "아우 → bola\n",
        "아이 → bola\n",
        "오이 → bodiring\n",
        "가수 → qo'shiqchi\n",
        "고기 → go'sht\n",
        "구두 → tufli\n",
        "나라 → davlat\n",
        "나무 → daraxt\n",
        "다리 → oyoq\n",
        "라디오 → radio\n",
        "머리 → bosh\n",
        "바나나 → banan\n",
        "바지 → shim\n",
        "소 → sigir\n",
        "아기 → chaqaloq\n",
        "어머니 → ona\n",
        "지도 → xarita\n",
        "모자 → bosh kiyim\n",
        "아버지 → ota\n",
        "허리 → bel\n",
        "지하 → yer osti\n",
        "야구 → beyzbol\n",
        "야자수 → palma\n",
        "이야기 → suxbat\n",
        "여자 → ayol\n",
        "혀 → til\n",
        "요가 → yo'ga\n",
        "요리 → ovqat pishirish\n",
        "휴지 → tualet qog'ozi\n",
        "우유 → sut\n",
        "카드 → karta\n",
        "코 → burun\n",
        "키 → balandlik\n",
        "타조 → tuyaqush\n",
        "토마토 → pomidor\n",
        "투우수 → motodor\n",
        "파리 → pashsha / Parij\n",
        "포도 → uzum\n",
        "우표 → pochta markasi\n",
        "차 → choy\n",
        "치마 → yubka\n",
        "고추 → qalampir\n",
        "커피 → kofe\n",
        "코트 → palto\n",
        "기차표 → poyezd bileti\n",
        "까치 → zog'cha\n",
        "꼬리 → dum\n",
        "코끼리 → fil\n",
        "따다 → uzmoq\n",
        "뜨다 → suzmoq\n",
        "머리띠 → abadok\n",
        "뿌리 → ildiz\n",
        "뼈 → suyak\n",
        "아빠 → ota\n",
        "싸다 → arzon\n",
        "쓰다 → yozmoq / foydalanmoq\n",
        "아저씨 → ko‘chadagi amaki\n",
        "짜다 → sho‘r\n",
        "찌다 → bug‘lamoq\n",
        "가짜 → qalbaki\n",
        "개미 → chumoli\n",
        "배 → qayiq\n",
        "새 → qush\n",
        "해 → quyosh\n",
        "게 → qisqichbaqa\n",
        "세수 → yuvinish\n",
        "그네 → arg‘imchoq\n",
        "카메라 → kamera\n",
        "얘기 → suhbat\n",
        "예쁘다 → chiroyli\n",
        "서예 → xattotlik\n",
        "시계 → soat\n",
        "과자 → pishiriq\n",
        "와이셔츠 → ko‘ylak\n",
        "화가 → jahl\n",
        "사과 → olma\n",
        "뭐 → nima\n",
        "줘요 → bermoq\n",
        "더워요 → issiq\n",
        "추워요 → sovuq\n"
        "돼지 → cho‘chqa\n",
        "왜 → nimaga\n",
        "웨이터 → ofitsiant\n",
        "스웨터 → svitr\n",
        "쇠고기 → mol go‘shti\n",
        "외우다 → yodlamoq\n",
        "회사 → firma\n",
        "귀 → quloq\n",
        "쉬다 → dam olmoq\n",
        "쥐 → sichqon\n",
        "가위 → qaychi\n",
        "의사 → doktor\n",
        "회의 → majlis\n",
        "수박 → tarvuz\n",
        "책 → kitob\n",
        "돈 → pul\n",
        "신문 → gazeta\n",
        "우산 → soyabon\n",
        "꽃 → gul\n",
        "물 → suv\n",
        "남자 → erkak\n",
        "컴퓨터 → kompyuter\n",
        "밥 → qaynatilgan guruch\n",
        "입 → og‘iz\n",
        "무릎 → tizza\n",
        "숲 → o‘rmon\n",
        "가방 → sumka\n"
        "공 → koptok\n"
        "냉장고 → muzlatgich\n"
        "창문 → deraza\n"
        "중국 → Xitoy\n"
        "일본 → Yaponiya\n"
        "미국 → AQSH\n"
        "한국 → Koreya\n"
        "프랑스 → Fransiya\n"
        "독일 → Germaniya\n"
        "호주 → Avstraliya\n"
        "영국 → Angliya\n"
        "빈칸 → bo‘sh joy\n",
        "맞다 → mos\n",
        "단어 → so‘z\n",
        "선생님 → o‘qituvchi\n",
        "학생 → o‘quvchi\n",
        "회사원 → firma ishchisi\n",
        "요리사 → oshpaz\n",
        "기자 → muxbir\n",
        "군인 → askar\n",
        "인사말 → salomlashish gapi\n",
        "만나다 → uchrashmoq\n",
        "반갑다 → xursand bo‘lmoq\n",
        "한국말 → koreys tili\n",
        "그림 → rasm\n",
        "이야기하다 → suhbatlashmoq\n",
        "저 → men\n",
        "씨 → janob / xonim\n",
        "네 → ha\n",
        "주부 → uy bekasi\n",
        "말하기 → gapirish\n",
        "어느 → qaysi\n",
        "캐나다 → Kanada\n",
        "국적 → millat\n",
        "묻다 → so‘ramoq\n",
        "인도 → Hindiston\n",
        "직업 → kasb\n",
        "아니요 → yo‘q\n",
        "여러분 → sizlar\n",
        "무엇 → nima\n",
        "러시아 → Rossiya\n",
        "파키스탄 → Pakistan\n",
        "친구 → dost\n",
        "명함 → ism karta\n",
        "이름 → ism\n",
        "전화번호 → telefon raqam\n",
        "영어 → ingliz tili\n",
        "블로그 → internetdagi blog\n",
        "찾다 → qidirmoq\n",
        "과제 → topshiriq\n",
        "문화 → madaniyat\n",
        "공책 → daftar\n",
        "볼펜 → ruchka\n",
        "연필 → qalam\n",
        "지우개 → o‘chirg‘ich\n",
        "사전 → lug‘at\n",
        "안경 → ko‘zoynak\n",
        "휴대폰 → telefon\n",
        "남자친구 → yigit o‘rtoq\n",
        "동전 → tanga\n",
        "한국어 → koreys tili\n",
        "여자 친구 → qiz o‘rtoq\n",
        "필통 → qalamdon\n",
        "전자사전 → elektron lug‘at\n",
        "한국어로 → koreys tilida\n",
        "자 → chizg‘ich\n",
        "잡지 → jurnal\n",
        "지갑 → hamyon\n",
        "여기 있어요 → marhamat\n",
        "좀 → iltimos\n",
        "콜라 → kola\n",
        "주스 → sharbat\n",
        "교통카드 → transport kartasi\n",
        "휴지 → salfetka\n",
        "어서 오세요 → xush kelibsiz\n",
        "사과 → olma\n",
        "오렌지 → apelsin\n",
        "영화 → kino\n",
        "우유 → sut\n",
        "바나나 → banan\n",
        "딸기 → qulupnay\n",
        "텔레비전 → televizor\n",
        "방 → non\n",
        "서울대학교 → Seul universiteti\n",
        "제 → mening\n",
        "침대 → kravat\n",
        "룸메이트 → xonadosh\n",
        "에어컨 → konditsioner\n",
        "물건 → narsa\n",
        "팀 → jamoa\n",
        "나누다 → bo‘lishmoq\n",
        "받다 → olmoq\n",
        "붙이다 → yopishtirmoq\n",
        "자다 → uxlamoq\n",
        "공부하다 → o‘rganmoq\n",
        "일하다 → ishlamoq\n",
        "운동하다 → sport bilan shug‘ullanmoq\n",
        "숙제를 하다 → uy vazifasini qilmoq\n",
        "옷을 사다 → kiyim sotib olmoq\n",
        "영화를 보다 → kino ko‘rmoq\n",
        "친구를 만나다 → do‘sti bilan uchrashmoq\n",
        "태권도를 배우다 → taekvondoni o‘rganmoq\n",
        "밥을 먹다 → ovqat yemoq\n",
        "커피를 마시다 → kofe ichmoq\n",
        "책을 읽다 → kitob o‘qimoq\n",
        "도서관 → kutubxona\n",
        "백화점 → univermag\n",
        "시장 → bozor\n",
        "공원 → park\n",
        "커피숍 → kafe\n",
        "극장 → kinoteatr\n",
        "학교 → maktab\n",
        "식당 → oshxona\n",
        "회사 → firma\n",
        "지금 → hozir\n",
        "하다 → qilmoq\n",
        "쉬다 → dam olmoq\n",
        "피자 → pitsa\n",
        "보다 → ko‘rmoq\n",
        "사다 → sotib olmoq\n",
        "먹다 → yemoq\n",
        "마시다 → ichmoq\n",
        "읽다 → o‘qimoq\n",
        "배우다 → o‘rganmoq\n",
        "일본어 → yapon tili\n",
        "아르바이트하다 → qo‘shimcha ish qilmoq\n",
        "오늘 → bugun\n",
        "그리고 → va\n",
        "어디 → qayer\n",
        "고기 → go‘sht\n",
        "프랑스어 → fransuz tili\n",
        "드라마 → drama\n",
        "그럼 → unday bo‘lsa\n",
        "스포츠 센터 → sport markazi\n",
        "차 → choy\n",
        "가르치다 → o‘qitmoq\n",
        "언어교육원 → til markazi\n",
        "공항 → aeroport\n",
        "우체국 → pochta\n",
        "불고기 → bulgogi\n",
        "노래방 → karaoke\n",
        "공항 → aeroport\n",
        "우체국 → pochta\n",
        "대사관 → elchixona\n",
        "은행 → bank\n",
        "가게 → do‘kon",
        "약국 → dorixona\n",
        "병원 → kasalxona\n",
        "미용실 → sartaroshxona\n",
        "앞 → oldi\n",
        "뒤 → orqasi\n",
        "인사동 → Insadong\n",
        "서울타워 → Seul minorasi\n",
        "명동 → Myongdong\n",
        "청계천 → Cheonggyecheon\n",
        "대학로 → Daehak-ro\n",
        "남산 → Namsan\n",
        "교실 → sinf xonasi\n",
        "찻집 → choyxona\n",
        "서울 → Seul\n",
        "시내 → shahar markazi\n",
        "구경하다 → tomosha qilmoq\n",
        "쇼핑하다 → xarid qilmoq\n",
        "연극 → teatr\n",
        "알다 → bilmoq\n",
        "잘 지내다 → ishlari yaxshi bo‘lmoq\n",
        "기숙사 → yotoqxona\n",
        "사진 → rasm\n",
        "매일 → har kuni\n",
        "그 → u\n",
        "반 → yarim\n",
        "사랑하다 → sevmoq\n",
        "서점 → kitob do‘koni\n",
        "빵집 → novvoyxona\n",
        "화장실 → hojatxona\n",
        "음식 → ovqat\n",
        "기념품 → suvenir\n",
        "숫자 → raqam\n",
        "월요일 → dushanba\n",
        "화요일 → seshanba\n",
        "수요일 → chorshanba\n",
        "목요일 → payshanba\n",
        "금요일 → juma\n",
        "토요일 → shanba\n",
        "일요일 → yakshanba\n",
        "주말 → hafta oxiri\n",
        "날짜 → sana\n",
        "요일 → hafta kuni\n",
        "며칠 → qaysi kun\n",
        "시험 → imtihon\n",
        "언제 → qachon\n",
        "무슨 → qaysi\n",
        "생일 → tug‘ilgan kun\n",
        "하고 → bilan",
        "크리스마스 → Rojdestvo\n",
        "파티 → bazm\n",
        "시간 → vaqt\n",
        "미안하다 → uzr so‘ramoq\n",
        "약속 → va’da\n",
        "같이 → birga\n",
        "어제 → kecha\n",
        "코엑스몰 → COEX savdo markazi\n",
        "선물 → sovg‘a\n",
        "세수하다 → yuvinmoq\n",
        "이를 닦다 → tish yuvmoq\n",
        "거기 → u joy\n",
        "산책하다 → sayr qilmoq\n",
        "사진을 찍다 → rasmga olmoq\n",
        "누구 → kim\n",
        "혼자 → yolg‘iz",
        "끝나다 → tugamoq\n",
        "강남역 → Gangnam bekati\n",
        "그래서 → shuning uchun\n",
        "내일 → ertaga\n",
        "스케줄 → kun tartibi\n",
        "지난주 → o‘tgan hafta\n",
        "양력 → quyosh kalendari\n",
        "음력 → oy kalendari\n",
        "설날 → Koreys yangi yili\n",
        "세배를 하다 → ta’zim qilmoq\n",
        "떡국 → tteokguk\n",
        "추석 → hosil bayrami\n",
        "차례를 지내다 → marosim o‘tkazmoq\n",
        "송편 → guruchli pishiriq\n",
        "연극 → teatr\n",
        "알다 → bilmoq\n",
        "잘 지내다 → ishlari yaxshi bo‘lmoq\n",
        "기숙사 → yotoqxona\n",
        "사진 → rasm\n",
        "매일 → har kuni\n",
        "그 → u\n",
        "반 → yarim\n",
        "사랑하다 → sevmoq\n",
        "서점 → kitob do‘koni\n",
        "빵집 → novvoyxona\n",
        "화장실 → hojatxona\n",
        "음식 → ovqat\n",
        "기념품 → suvenir\n",
        "숫자 → raqam\n",
        "월요일 → dushanba\n",
        "화요일 → seshanba\n",
        "수요일 → chorshanba\n",
        "목요일 → payshanba\n",
        "금요일 → juma\n",
        "토요일 → shanba\n",
        "일요일 → yakshanba\n",
        "주말 → hafta oxiri\n",
        "날짜 → sana\n",
        "요일 → hafta kuni\n",
        "며칠 → qaysi kun\n",
        "시험 → imtihon\n",
        "언제 → qachon\n",
        "무슨 → qaysi\n",
        "생일 → tug‘ilgan kun\n",
        "하고 → bilan\n",
        "크리스마스 → Rojdestvo\n",
        "파티 → bazm\n",
        "시간 → vaqt\n",
        "미안하다 → uzr so‘ramoq\n",
        "약속 → va’da\n",
        "같이 → birga\n",
        "어제 → kecha\n",
        "코엑스몰 → seul savdo markazi\n",
        "선물 → sovg‘a\n",
        "세수하다 → yuvinmoq\n",
        "이를 닦다 → tish yuvmoq\n",
        "거기 → u joy\n",
        "산책하다 → sayr qilmoq\n",
        "사진을 찍다 → rasmga olmoq\n",
        "누구 → kim",
        "혼자 → yolg‘iz\n",
        "끝나다 → tugamoq\n",
        "강남역 → Gangnam bekati\n",
        "그래서 → shuning uchun\n",
        "내일 → ertaga\n",
        "스케줄 → kun tartibi\n",
        "지난주 → o‘tgan hafta\n",
        "양력 → quyosh kalendari\n",
        "음력 → oy kalendari\n",
        "설날 → Koreys yangi yili\n",
        "세배를 하다 → ta’zim qilmoq\n",
        "떡국 → tteokguk\n",
        "추석 → hosil bayrami\n"
    )

@bot.message_handler(content_types=['text'])
def translate(message):
    text = message.text.lower().strip()

    if text in ko_uz:
        bot.reply_to(message, f"🇰🇷 → 🇺🇿\n**{text}** = {ko_uz[text]}", parse_mode="Markdown")
    elif text in uz_ko:
        bot.reply_to(message, f"🇺🇿 → 🇰🇷\n**{text}** = {uz_ko[text]}", parse_mode="Markdown")
    else:
        # Qisman qidirish
        found = False
        for k, v in ko_uz.items():
            if text in k:
                bot.reply_to(message, f"🇰🇷 → 🇺🇿\n**{k}** = {v}", parse_mode="Markdown")
                found = True
                break
        if not found:
            for k, v in uz_ko.items():
                if text in k:
                    bot.reply_to(message, f"🇺🇿 → 🇰🇷\n**{k}** = {v}", parse_mode="Markdown")
                    found = True
                    break
        
        if not found:
            bot.reply_to(message, "❌ Bu so'z lug'atda topilmadi. Biz yangi so'zlarni qo'shish ustida ishlayapmiz!")

import time

if __name__ == '__main__':
    print("Bot ishga tushmoqda...")
    while True:
        try:
            bot.polling(none_stop=True, timeout=60)
        except Exception as e:
            print(f"Xatolik yuz berdi: {e}")
            print("15 soniyadan so'ng qayta urinib ko'riladi...")
            time.sleep(15)
